# BL40A2010 Introduction to IoT-Based Systems

## Assignment 6, 27.02.2023

### Author: Semen Kovesnikov

**Prisoner's dilemma** is a standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher while working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and named it "prisoner's dilemma", presenting it as follows:

"Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of communicating with the other. The prosecutors lack sufficient evidence to convict the pair on the principal charge, but they have enough to convict both on a lesser charge. Simultaneously, the prosecutors offer each prisoner a bargain. Each prisoner is given the opportunity either to betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The possible outcomes are:

- If A and B each betray the other (not-cooperating to each other), each of them serves $z$ years in prison (payoff of $-z$)
- If A betrays B (not-cooperating with B) but B remains silent (cooperating with A), A will serve $y$ years in prison (payoff $-y$) and B will serve $w$ years  (payoff of $-w$).
- If B betrays A (not-cooperating with A) but A remains silent (cooperating with B), B will serve $y$ years in prison (payoff $-y$) and A will serve $w$ years  (payoff of $-w$).
- If A and B both remain silent, both of them will serve $x$ years in prison (payoff of $-x$)."

The payoff table is presented below. 

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|                |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|                |  $B\rightarrow -w$   | $B\rightarrow -z$  |

**However, this is only a *Prisoner's Dilemma GAME* for A GIVEN RELATION between the years in prison (payoffs) as to be studied next.**

ps. Text adapted from [Wikipedia](https://en.wikipedia.org/wiki/Prisoner's_dilemma).

**(1) Consider the Prisoner's dilemma description given above.**

**(a) What is the relation between the payoffs values $x\geq 0$, $y\geq 0$, $w\geq 0$ and $z \geq 0$ so that the game can be classified as [Prisoner's Dilemma](https://en.wikipedia.org/wiki/Prisoner's_dilemma)?**

**(b) Verify the results (i.e., the proposed inequality) with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html). Please provide one example when the inequality holds and one it does not (check my example for Dove and Hawyk game).**

In [1]:
#lib import
import numpy as np
import nashpy as nash

If neither A nor B confess, then they will both bear less amount of years, than if they both defect, and more if only one confesses. Hence, $y<x<z$.
However, if one betrays another, and the second one stays silent, then the silent one gets more years than in case of both silent. Thus, $z<w$.
This gives us

$y<x<z<w$

In [4]:
A=[[-3, -5],[-2, -4]]
B=[[-3, -2],[-5, -4]]
prisonners_dilemma=nash.Game(A,B)
prisonners_dilemma

Bi matrix game with payoff matrices:

Row player:
[[-3 -5]
 [-2 -4]]

Column player:
[[-3 -2]
 [-5 -4]]

In [7]:
eq=prisonners_dilemma.support_enumeration()
list(eq)

[(array([0., 1.]), array([0., 1.]))]

From the result, it can be seen that they will not cooperate.

In [12]:
A=[[0, -5],[-1, -3]]
B=[[0, -1],[-5, -3]]
prisonners_dilemma=nash.Game(A,B)
eq=prisonners_dilemma.support_enumeration()
list(eq)

[(array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.])),
 (array([0.66666667, 0.33333333]), array([0.66666667, 0.33333333]))]

**(2) Justify why the game from the previous exercise is or is not a good (reasonable) model when $A$ and $B$ are:**

**1. Two trained members from the army when they are in prison.**


**2. Competitive companies in the market discussing standardization.**


**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**


**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**

**ps. You need to think about the assumption used in Game Theory and in the Prisoner's dilemma problem setting.**

Answer:
1. The model isn't representative, as it's likely that trained members will cooperate, knowing the best outcome, because they are used to behave as a group, and not like an individual.
2. Here it depends. It may be that it's much more profitable to push your own standard, so that others have to adopt it. However, if a completely new standard needed, then a cooperation is more appealing, as the spendings on development can be shared between companies. Otherwise the CAPEX may be too high. Of course, the revenue will be split as well, but it's still some profit.
3. Not really, as energy efficiency of one algorithm isn't connected to an other, then it's not the case of Prisonners dilemma.
4. When it comes to profit maximixation, each algorithm will be working for its own benifit, hence they will be in rival. But it's much better for them to cooperate to reach the common goal. The type of source also matters, as it can be the same or not for the algorithms.