# BL40A2010 Introduction to IoT-Based Systems

## Tutorial 6: *Game theory and decision making*

## Author: Pedro Nardelli

### Installing a missing library [Nashpy](https://nashpy.readthedocs.io/en/stable/)

[How to do it in Azure](https://notebooks.azure.com/help/jupyter-notebooks/package-installation/python)

In [1]:
#Installing a missing library
! pip install nashpy==0.0.21

  Created wheel for nashpy: filename=nashpy-0.0.19-cp36-none-any.whl size=11561 sha256=231707920a98e69899a1fe99975d564cbeb1cc6d7d7a2b88c03ecc21847c28a6
  Stored in directory: /home/nbuser/.cache/pip/wheels/18/e9/56/2d04d01a6969d167f86d3afcb3d128c0b43d0d73ea471c835b
Successfully built nashpy
You should consider upgrading via the 'pip install --upgrade pip' command.


In [15]:
#Import libraries
import matplotlib.pyplot as plt 
import numpy as np
import nashpy as nash

### This tutorial is an adaptation from Chapters [1](https://vknight.org/gt/chapters/01/),  [2](https://vknight.org/gt/chapters/02/) and  [3](https://vknight.org/gt/chapters/03/) from [Vincent  Knight](https://vknight.org/) course in Game Theory at Cardiff University. 

# Normal Form Games

[Video](https://youtu.be/VDZ4I4IoFss?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

Game theory is the study of interactive decision making. Consider the following situation:

> Two friends must decide what movie to watch at the cinema. Alice would like to watch a sport movie and Bob would like to watch a comedy. Importantly they would both rather spend their evening together then apart.

To represent this mathematically we will associate **utilities** to the 4 possible outcomes:

1. Alice watches a sport movie, Bob watches a comedy: Alice receives a utility of $1$ and Bob a utility of $1$.
2. Alice watches a comedy, Bob watches a sport movice: Alice receives a utility of $0$ and Bob a utility of $0$.
3. Alice and Bob both watch a sport movie: Alice receives a utility of $3$ and Bob a utility of $2$.
4. Alice and Bob both watch a comedy: Alice receives a utility of $2$ and Bob a utility of $3$.

This is referred to as the "battle of the sexes" and we will represent it using two matrices, $A$ will represent the utilities of Alice:

$$
A = 
\begin{pmatrix}
3 & 1\\
0 & 2
\end{pmatrix}
$$

and matrix $B$ will represent the utilities of Bob:

$$
B = 
\begin{pmatrix}
2 & 1\\
0 & 3
\end{pmatrix}
$$

We refer to **Alice as the row player** and **Bob as the column player**: 

- The row player chooses which row of the matrices the players will gain their utilities;
- The column player chooses which column of the matrices the player will gain their utilities.

Thus if the row player (Alice) chooses the first row (this corresponds to a sport movie) and the column player (Bob) chooses the second column (this corresponds to a comedy):

- The row player receives a utility of $A_{12}=1$
- The column player receives a utility of $B_{12}=1$

This representation of the stategic interaction between Alice and Bob is called a **Normal Form Game**.

We can use Python to represent these games, we will use the `nashpy` library to do so and we start by building our two matrices:

In [16]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]

In [17]:
battle_of_the_sexes = nash.Game(A, B)
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

## Hawk Dove game 

[Video](https://youtu.be/_7HtcsVB2uU?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

> Suppose two birds of prey must share a limited resource. The birds can act like a hawk or a dove. Hawks always fight over the resource to the point of exterminating a fellow hawk and/or take a majority of the resource from a dove. Two doves can share the resource.



This corresponds to:

$$
A =
\begin{pmatrix}
    0 & 3\\
    1 & 2
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    0 & 1\\
    3 & 2
\end{pmatrix}
$$

In [18]:
A = [[0, 3], [1, 2]]
B = [[0, 1], [3, 2]]
hawk_dove = nash.Game(A, B)
hawk_dove

Bi matrix game with payoff matrices:

Row player:
[[0 3]
 [1 2]]

Column player:
[[0 1]
 [3 2]]

## Pigs

[Video](https://youtu.be/ORGYJdqZkX0?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

> Consider two pigs. One dominant pig and one subservient pig. These pigs share a pen. There is a lever in the pen that delivers food but if either pig pushes the lever it will take them a little while to get to the food. If the dominant pig pushes the lever, the subservient pig has some time to eat most of the food before being pushed out of the way. If the subservient pig push the lever, the dominant pig will eat all the food. Finally if both pigs go to push the lever the subservient pig will be able to eat a third of the food.

This corresponds to:

$$
A =
\begin{pmatrix}
    4 & 2\\
    6 & 0
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    2 & 3\\
    -1 & 0
\end{pmatrix}
$$

In [6]:
A = [[4, 2], [6, 0]]
B = [[2, 3], [-1, 0]]
pigs = nash.Game(A, B)
pigs

Bi matrix game with payoff matrices:

Row player:
[[4 2]
 [6 0]]

Column player:
[[ 2  3]
 [-1  0]]

## Matching pennies

[Video](https://youtu.be/80ImlktaeeY?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

>Consider two players who can choose to display a coin either Heads facing up or Tails facing up. If both players show the same face then player 1 wins, if not then player 2 wins.

This corresponds to:

$$
A =
\begin{pmatrix}
    1 & -1\\
    -1 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -1 & 1\\
    1 & -1
\end{pmatrix}
$$

In [7]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]
matching_pennies = nash.Game(A, B)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

As indicated by `nashpy`, this is a `Zero sum game`: 

$$
A + B = 0
$$

---

## Definition of a zero sum game

[Video](https://youtu.be/wUh1KFupLFI?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

A two player normal form game with payoff matrices $A, B$ is called **zero sum** iff:

$$
A = -B
$$

---

To define a zero sum game using `nashpy` we can pass a single payoff matrix (it infers what the other will be):

In [8]:
A = [[1, -1], [-1, 1]]
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

# Player strategies

---

## Definition of mixed strategies

[Video](https://youtu.be/D_UID1t94UI?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

A mixed strategy for a player with strategy set $S$ is denoted by $\sigma \in [0,1]_{\mathbb{R}}^{|S|}$ and corresponds to a probability distribution over the pure strategies of player $i$. So:

$$
\sum_{i=1}^{|S|}\sigma_i = 1
$$

---

The expected score of a player can then be calculated as a measure over the probability distributions.

---

## Calculating utilities

Considering a game $(A, B)\in\mathbb{{R^{m \times n}}^2}$, if $\sigma_r$ and $\sigma_c$ are the mixed strategies for the row/column player (respectively). The utility to the row player is:

$$
u_r(\sigma_r, \sigma_c) = \sum_{i=1}^m\sum_{j=1}^nA_{ij}{\sigma_r}_i{\sigma_c}_j
$$

and the utility to the column player is:

$$
u_c(\sigma_r, \sigma_c) = \sum_{i=1}^m\sum_{j=1}^nB_{ij}{\sigma_r}_i{\sigma_c}_j
$$

This comes from:

- The probability of being in a given cell of $A$ or $B$: ${\sigma_r}_i{\sigma_c}_j$
- The value of the particular cell: $A_{ij}$ or $B_{ij}$

---

As an example consider the matching pennies game:

$$
A =
\begin{pmatrix}
    1 & -1\\
    -1 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -1 & 1\\
    1 & -1
\end{pmatrix}
$$

with the following mixed strategies:

$$
\sigma_r = (.2, .8)
\qquad
\sigma_c = (.6, .4)
$$

We have:

$$
u_r(\sigma_r, \sigma_c) = 0.2 \times 0.6 \times 1 + 0.2 \times 0.4 \times (-1) + 0.8 \times 0.6 \times (-1) + 0.8 \times 0.4 \times 1=-0.12,
$$

$$
u_c(\sigma_r, \sigma_c) = 0.2 \times 0.6 \times (-1) + 0.2 \times 0.4 \times 1 + 0.8 \times 0.6 \times 1 + 0.8 \times 0.4 \times (-1)=0.12.
$$

---

## Linear algebraic calculation

[Video](https://youtu.be/X-n0e58vfYw?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

Note that we can rearrange the expressions for the utilities:

$$
u_r(\sigma_r, \sigma_c) = \sum_{i=1}^m{\sigma_r}_i\sum_{j=1}^nA_{ij}{\sigma_c}_j
$$

$$
u_c(\sigma_r, \sigma_c) = \sum_{i=1}^m{\sigma_r}_i\sum_{j=1}^nB_{ij}{\sigma_c}_j
$$

in turn this corresponds to the matrix vector product:

$$
u_r(\sigma_r, \sigma_c) = {\sigma_r}A\sigma_c^T
$$

$$
u_c(\sigma_r, \sigma_c) = {\sigma_r}B\sigma_c^T
$$

We can use numpy to verify this calculation:

In [19]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])
sigma_r = np.array([.2, .8])
sigma_c = np.array([.6, .4])
np.dot(sigma_r, np.dot(A, sigma_c)), np.dot(sigma_r, np.dot(B, sigma_c))

(-0.11999999999999998, 0.11999999999999998)

We can use nashpy directly.

In [20]:
matching_pennies = nash.Game(A, B)
matching_pennies[sigma_r, sigma_c]

array([-0.12,  0.12])

## Definition of a strictly dominated strategy

[Video](https://youtu.be/KOSSfH_Z3F0?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

In a two player game $(A, B)\in\mathbb{{R^{m \times n}}^2}$ a strategy $s$ is _dominated_ by strategy $\bar s$ if for all strategies of the other player $t$:

$$
u(s, t) < u(\bar s, t)
$$

---

For example if we consider the Prisoner's Dilemma:

$$
A =
\begin{pmatrix}
    3 & 0\\
    5 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    3 & 5\\
    0 & 1
\end{pmatrix}
$$

- we see that $A_{2j} > A_{1j}$ for all $j$, so we can say that the row players' first strategy is dominated by its second strategy.
- we see that $B_{i2} > B_{i1}$ for all $i$, so we can say that the column players' first strategy is dominated by its second strategy.

---

## Definition of a weakly dominated strategy

[Video](https://youtu.be/uJPcXIDDO8M?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

In a two player game $(A, B)\in\mathbb{{R^{m \times n}}^2}$ a strategy $s$ is _weakly dominated_ by strategy $\bar s$ if for all strategies of the other player $t$:

$$
u(s, t) \leq u(\bar s, t)
$$

**and there exists** a $t'$ such that:

$$
u(s, t') < u(\bar s, t')
$$

---

For example if we consider the modified version of the previous game:

$$
A =
\begin{pmatrix}
    3 & 0\\
    3 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    3 & 3\\
    0 & 1
\end{pmatrix}
$$

- we see that $A_{2j} \geq A_{1j}$ for all $j$ **and** $A_{22} > A_{12}$, so we can say that the row players' first strategy is weakly dominated by its second strategy.
- we see that $B_{i2} \geq B_{i1}$ for all $i$ **and** $B_{22} > B_{21}$, so we can say that the column players' first strategy is weakly dominated by its second strategy.

We can use `numpy` to verify if a strategy is weakly/strictly dominated:

In [11]:
A = np.array([[3, 0], [3, 1]])
B = np.array([[3, 3], [0, 1]])

In [12]:
# Verify that first row is weakly dominated by second row
all(A[0,:] <= A[1,:]) and any(A[0,:] < A[1,:])

True

In [13]:
# Verify that first column is weakly dominated by second column
all(B[:,0] <= B[:,1]) and any(B[:,0] < B[:,1])

True

## Definition  of common knowledge of rationality

[Video](https://youtu.be/7FZAWCI_q60?list=PLnC5h3PY-znxMsG0TRYGOyrnEO-QhVwLb)

An important aspect of Game Theory and the tool that we have in fact been using so far is to assume that players are rational. However we can (and need) to go further:

- The players are rational;
- The players all know that the other players are rational;
- The players all know that the other players know that they are rationals;
...


This chain of assumptions is called Common Knowledge of Rationality (CKR). By applying the CKR assumption we can attempt to predict rational behaviour through the iterated elimination of weakly dominated strategies. This process is called **rationalisation**.

Let us consider the following game:

$$
A =
\begin{pmatrix}
    10 & 5 & 1\\
    10 & 5 & 4
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    1 & 1 & -2\\
    1 & 0 & 2
\end{pmatrix}
$$

We see that the rows players' first strategy is weakly dominated by its second.

In [14]:
A = np.array([[10, 5, 1], [10, 5, 4]])
B = np.array([[1, 1, -2], [1, 0, 2]])
all(A[0,:] <= A[1,:]) and any(A[0,:] < A[1,:])

True

Once we have removed that strategy the game reduces to:

$$
A =
\begin{pmatrix}
    10 & 5 & 4
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    1 & 0 & 2
\end{pmatrix}
$$

and now we see that the column players' third strategy would dominate the other two.

Thus a prediction of rational behaviour would be the strategy profile: $(r_2, c_3)$.

Not all games allow for prediction of rational behaviour through rationalisation **and** for some games the prediction will change depending on the order of the elimination.